# Generated by Django 5.0.1 on 2025-12-02 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="empreintedigitale",
            name="fichier",
            field=models.FileField(
                blank=True,
                help_text="Fichier empreinte stocké sur MinIO ou localement",
                null=True,
                upload_to="empreintes/",
            ),
        ),
        migrations.AlterField(
            model_name="empreintedigitale",
            name="template",
            field=models.TextField(blank=True, null=True),
        ),
    ]
