# Generated by Django 5.0.1 on 2025-12-02 02:03

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_empreintedigitale_fichier_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Revenu",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "solde",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "citoyen",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revenu",
                        to="api.citoyen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Revenu",
                "verbose_name_plural": "Revenus",
                "db_table": "revenus",
            },
        ),
        migrations.CreateModel(
            name="Denonciation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("vol", "Vol"),
                            ("agression", "Agression"),
                            ("accident", "Accident"),
                            ("incendie", "Incendie"),
                            ("autre", "Autre"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("localisation", models.CharField(max_length=500)),
                ("coordonnees_gps", models.JSONField(blank=True, null=True)),
                (
                    "preuve_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("audio", "Audio"),
                            ("video", "Vidéo"),
                            ("aucun", "Aucun"),
                        ],
                        default="aucun",
                        max_length=50,
                    ),
                ),
                ("preuve_url", models.URLField(blank=True, null=True)),
                (
                    "preuve_fichier",
                    models.FileField(
                        blank=True, null=True, upload_to="denonciations/preuves/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("verified", "Vérifiée"),
                            ("rejected", "Rejetée"),
                            ("en_cours", "En cours de traitement"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("reponse", models.TextField(blank=True, null=True)),
                ("reponse_date", models.DateTimeField(blank=True, null=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "citoyen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="denonciations",
                        to="api.citoyen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dénonciation",
                "verbose_name_plural": "Dénonciations",
                "db_table": "denonciations",
                "ordering": ["-date_creation"],
                "indexes": [
                    models.Index(
                        fields=["citoyen", "status"],
                        name="denonciatio_citoyen_59ad40_idx",
                    ),
                    models.Index(
                        fields=["type", "status"], name="denonciatio_type_8ad613_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("cni", "CNI"),
                            ("passeport", "Passeport"),
                            ("extrait_naissance", "Extrait de naissance"),
                            ("casier_judiciaire", "Casier judiciaire"),
                            ("acte_mariage", "Acte de mariage"),
                            ("acte_deces", "Acte de décès"),
                            ("certificat_residence", "Certificat de résidence"),
                            ("permis_conduire", "Permis de conduire"),
                            ("carte_sejour", "Carte de séjour"),
                            ("autre", "Autre"),
                        ],
                        max_length=50,
                    ),
                ),
                ("numero", models.CharField(max_length=200)),
                ("date_emission", models.DateField()),
                ("date_expiration", models.DateField(blank=True, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("valide", "Valide"),
                            ("expire", "Expiré"),
                            ("en_attente", "En attente"),
                        ],
                        default="valide",
                        max_length=50,
                    ),
                ),
                ("document_url", models.URLField(blank=True, null=True)),
                (
                    "fichier",
                    models.FileField(
                        blank=True,
                        help_text="Fichier PDF ou image du document",
                        null=True,
                        upload_to="documents/",
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "citoyen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="api.citoyen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "db_table": "documents",
                "ordering": ["-date_emission"],
                "indexes": [
                    models.Index(
                        fields=["citoyen", "type"], name="documents_citoyen_7722a1_idx"
                    ),
                    models.Index(fields=["statut"], name="documents_statut_e8e372_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Plainte",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("reçue", "Reçue"), ("déposée", "Déposée")],
                        max_length=50,
                    ),
                ),
                ("objet", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "commissariat",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("localisation", models.JSONField(blank=True, null=True)),
                (
                    "amende",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("en_cours", "En cours"),
                            ("resolue", "Résolue"),
                            ("rejetee", "Rejetée"),
                            ("en_attente", "En attente"),
                        ],
                        default="en_attente",
                        max_length=50,
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "citoyen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plaintes",
                        to="api.citoyen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plainte",
                "verbose_name_plural": "Plaintes",
                "db_table": "plaintes",
                "ordering": ["-date_creation"],
                "indexes": [
                    models.Index(
                        fields=["citoyen", "type"], name="plaintes_citoyen_c2dd98_idx"
                    ),
                    models.Index(fields=["status"], name="plaintes_status_8377fc_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("gain", "Gain"),
                            ("transfert", "Transfert"),
                            ("retrait", "Retrait"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "destinataire",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("complete", "Complète"),
                            ("echec", "Échec"),
                        ],
                        default="en_attente",
                        max_length=50,
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("date_completion", models.DateTimeField(blank=True, null=True)),
                ("reference", models.CharField(blank=True, max_length=100, null=True)),
                ("details", models.JSONField(blank=True, null=True)),
                (
                    "citoyen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="api.citoyen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
                "db_table": "transactions",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["citoyen", "type"],
                        name="transaction_citoyen_e91419_idx",
                    ),
                    models.Index(
                        fields=["statut", "date"], name="transaction_statut_91477e_idx"
                    ),
                ],
            },
        ),
    ]
