# Generated by Django 5.0.1 on 2025-12-02 02:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_revenu_denonciation_document_plainte_transaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlerteUrgence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("danger_imminent", "Danger imminent"),
                            ("agression", "Agression"),
                            ("accident", "Accident"),
                            ("maladie", "Maladie/Urgence médicale"),
                            ("autre", "Autre"),
                        ],
                        default="danger_imminent",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "localisation",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("coordonnees_gps", models.JSONField()),
                ("brigades_notifiees", models.JSONField(default=list)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("envoyee", "Envoyée"),
                            ("en_cours", "En cours de traitement"),
                            ("prise_en_charge", "Prise en charge"),
                            ("resolue", "Résolue"),
                            ("annulee", "Annulée"),
                        ],
                        default="envoyee",
                        max_length=50,
                    ),
                ),
                (
                    "agent_charge_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "agent_charge_nom",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "brigade_charge_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "brigade_charge_nom",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_prise_en_charge", models.DateTimeField(blank=True, null=True)),
                ("date_resolution", models.DateTimeField(blank=True, null=True)),
                (
                    "citoyen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alertes_urgence",
                        to="api.citoyen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerte d'Urgence",
                "verbose_name_plural": "Alertes d'Urgence",
                "db_table": "alertes_urgence",
                "ordering": ["-date_creation"],
                "indexes": [
                    models.Index(
                        fields=["citoyen", "statut"],
                        name="alertes_urg_citoyen_d783e8_idx",
                    ),
                    models.Index(
                        fields=["statut", "date_creation"],
                        name="alertes_urg_statut_147475_idx",
                    ),
                ],
            },
        ),
    ]
